#!/usr/bin/env python3
"""
扩展词库到2000+单词，按词长分配50个难度等级
"""
import json
import random

random.seed(42)

# ---- 现有词库英中对照表（~520词） ----
MEANINGS = {
    "apple": "苹果", "banana": "香蕉", "cat": "猫", "dog": "狗", "egg": "鸡蛋",
    "fish": "鱼", "girl": "女孩", "hand": "手", "ice": "冰", "jump": "跳",
    "king": "国王", "lion": "狮子", "moon": "月亮", "nest": "巢", "orange": "橙子",
    "panda": "熊猫", "queen": "女王", "rain": "雨", "sun": "太阳", "tree": "树",
    "umbrella": "雨伞", "violin": "小提琴", "water": "水", "yellow": "黄色",
    "zebra": "斑马", "bird": "鸟", "book": "书", "chair": "椅子", "door": "门",
    "eye": "眼睛", "face": "脸", "grass": "草", "heart": "心", "island": "岛屿",
    "juice": "果汁", "kite": "风筝", "lake": "湖", "milk": "牛奶", "nose": "鼻子",
    "able": "能够", "about": "关于", "above": "在...上面", "accept": "接受",
    "across": "穿过", "action": "行动", "active": "积极的", "add": "添加",
    "afraid": "害怕的", "after": "在...之后", "again": "再次", "age": "年龄",
    "ago": "以前", "agree": "同意", "air": "空气", "all": "全部", "almost": "几乎",
    "alone": "独自", "along": "沿着", "already": "已经", "also": "也",
    "always": "总是", "among": "在...之中", "amount": "数量", "animal": "动物",
    "answer": "答案", "any": "任何", "appear": "出现", "area": "区域",
    "arm": "手臂", "around": "周围", "arrive": "到达", "art": "艺术",
    "ask": "问", "baby": "婴儿", "back": "背部", "bad": "坏的", "bag": "袋子",
    "ball": "球", "bank": "银行", "base": "基础", "bath": "洗澡",
    "beach": "海滩", "bear": "熊", "beat": "打败", "beautiful": "美丽的",
    "became": "成为", "because": "因为", "become": "变得", "been": "曾经是",
    "before": "之前", "began": "开始", "begin": "开始", "behind": "在...后面",
    "believe": "相信", "below": "在...下面", "beside": "在...旁边",
    "better": "更好的", "between": "在...之间", "big": "大的", "birth": "出生",
    "black": "黑色", "blood": "血液", "blue": "蓝色", "board": "木板",
    "boat": "船", "body": "身体", "boil": "煮沸", "bone": "骨头",
    "born": "出生", "both": "两者", "bottom": "底部", "bought": "购买",
    "box": "盒子", "boy": "男孩", "branch": "树枝", "bread": "面包",
    "break": "打破", "bring": "带来", "broad": "宽阔的", "broke": "打破",
    "brother": "兄弟", "brown": "棕色", "brush": "刷子", "build": "建造",
    "burn": "燃烧", "bus": "公共汽车", "business": "商业", "busy": "忙碌的",
    "buy": "购买", "cabin": "小屋", "call": "打电话", "came": "来",
    "camp": "露营", "can": "能够", "capital": "首都", "captain": "队长",
    "car": "汽车", "card": "卡片", "care": "关心", "careful": "仔细的",
    "carry": "携带", "case": "情况", "catch": "抓住", "cause": "原因",
    "cell": "细胞", "center": "中心", "century": "世纪", "certain": "确定的",
    "chance": "机会", "change": "改变", "chapter": "章节",
    "character": "角色", "charge": "收费", "cheap": "便宜的", "check": "检查",
    "chicken": "鸡肉", "child": "孩子", "children": "孩子们", "choose": "选择",
    "church": "教堂", "circle": "圆圈", "city": "城市", "claim": "声称",
    "class": "班级", "clean": "干净的", "clear": "清晰的", "climb": "爬",
    "clock": "时钟", "close": "关闭", "cloth": "布", "cloud": "云",
    "coach": "教练", "coal": "煤", "coast": "海岸", "coat": "外套",
    "code": "代码", "coffee": "咖啡", "cold": "冷的", "collect": "收集",
    "college": "学院", "color": "颜色", "come": "来", "common": "常见的",
    "company": "公司", "complete": "完成", "computer": "电脑",
    "condition": "条件", "consider": "考虑", "continue": "继续",
    "control": "控制", "cool": "凉爽的", "copy": "复制", "corn": "玉米",
    "corner": "角落", "correct": "正确的", "cost": "成本", "cotton": "棉花",
    "could": "能够", "count": "数数", "country": "国家", "course": "课程",
    "court": "法院", "cover": "覆盖", "cow": "奶牛", "create": "创造",
    "crop": "农作物", "cross": "穿过", "crowd": "人群", "cry": "哭",
    "current": "当前的", "cut": "切", "dad": "爸爸", "dance": "跳舞",
    "dark": "黑暗的", "data": "数据", "daughter": "女儿", "day": "天",
    "dead": "死的", "deal": "处理", "dear": "亲爱的", "death": "死亡",
    "decide": "决定", "deep": "深的", "degree": "程度", "deliver": "交付",
    "demand": "需求", "department": "部门", "describe": "描述",
    "desert": "沙漠", "design": "设计", "determine": "决定", "develop": "发展",
    "did": "做", "die": "死", "difference": "差异", "different": "不同的",
    "difficult": "困难的", "dinner": "晚餐", "direct": "直接的",
    "discuss": "讨论", "do": "做", "doctor": "医生", "does": "做",
    "dollar": "美元", "done": "完成", "down": "向下", "draw": "画",
    "dream": "梦想", "dress": "连衣裙", "drink": "喝", "drive": "驾驶",
    "drop": "掉落", "dry": "干燥的", "duck": "鸭子", "during": "在...期间",
    "each": "每个", "early": "早的", "earth": "地球", "east": "东方",
    "easy": "容易的", "eat": "吃", "edge": "边缘", "education": "教育",
    "effect": "效果", "eight": "八", "either": "任一", "electric": "电的",
    "else": "否则", "end": "结束", "enemy": "敌人", "energy": "能量",
    "enjoy": "享受", "enough": "足够的", "enter": "进入", "entire": "整个的",
    "equal": "平等的", "escape": "逃跑", "even": "甚至", "evening": "傍晚",
    "event": "事件", "ever": "曾经", "every": "每个", "exact": "精确的",
    "example": "例子", "exercise": "练习", "exist": "存在", "expect": "期望",
    "experience": "经验", "fact": "事实", "fail": "失败", "fair": "公平的",
    "fall": "落下", "family": "家庭", "famous": "著名的", "far": "远的",
    "farm": "农场", "fast": "快速的", "father": "父亲", "fear": "恐惧",
    "feed": "喂养", "feel": "感觉", "feet": "脚", "few": "几个",
    "field": "领域", "fight": "战斗", "figure": "数字", "fill": "填充",
    "film": "电影", "final": "最终的", "find": "找到", "fine": "好的",
    "finger": "手指", "finish": "完成", "fire": "火", "firm": "坚定的",
    "first": "第一", "fit": "适合", "five": "五", "floor": "地板",
    "flower": "花", "fly": "飞", "follow": "跟随", "food": "食物",
    "foot": "脚", "for": "为了", "force": "力量", "foreign": "外国的",
    "forest": "森林", "forget": "忘记", "form": "形式", "forward": "向前",
    "found": "找到", "four": "四", "free": "自由的", "fresh": "新鲜的",
    "friend": "朋友", "from": "从", "front": "前面", "fruit": "水果",
    "full": "满的", "fun": "乐趣", "funny": "有趣的", "future": "未来",
    "game": "游戏", "gave": "给", "general": "一般的", "get": "得到",
    "give": "给", "glad": "高兴的", "glass": "玻璃", "go": "去",
    "god": "上帝", "gold": "黄金", "gone": "走了", "good": "好的",
    "got": "得到", "govern": "统治", "government": "政府", "grand": "宏伟的",
    "gray": "灰色的", "great": "伟大的", "green": "绿色的", "grew": "成长",
    "ground": "地面", "group": "组", "grow": "成长", "guess": "猜测",
    "guide": "指导", "hair": "头发", "half": "一半", "hall": "大厅",
    "hang": "悬挂", "happen": "发生", "happy": "快乐的", "hard": "困难的",
    "has": "有", "hat": "帽子", "have": "有", "head": "头", "hear": "听到",
    "heat": "热量", "heavy": "重的", "held": "握着", "help": "帮助",
    "her": "她的", "here": "这里", "high": "高的", "hill": "小山",
    "him": "他", "his": "他的", "history": "历史", "hit": "击中",
    "hold": "握住", "hole": "洞", "home": "家", "hope": "希望",
    "horse": "马", "hospital": "医院", "hot": "热的", "hotel": "酒店",
    "hour": "小时", "house": "房子", "how": "如何", "however": "然而",
    "huge": "巨大的", "human": "人类", "hundred": "百", "husband": "丈夫",
    "idea": "主意", "image": "图像", "imagine": "想象", "important": "重要的",
    "in": "在...里面", "include": "包括", "indeed": "确实",
    "indicate": "表明", "industry": "工业", "information": "信息",
    "inside": "内部", "instead": "代替", "interest": "兴趣",
    "international": "国际的", "into": "进入", "involve": "涉及",
    "is": "是", "issue": "问题", "it": "它", "item": "项目",
    "its": "它的", "itself": "它自己", "just": "只是", "keep": "保持",
    "kept": "保持", "kill": "杀死", "kind": "善良的", "kitchen": "厨房",
    "knew": "知道", "know": "知道", "knowledge": "知识", "lady": "女士",
    "laid": "放置", "land": "土地", "language": "语言", "large": "大的",
    "last": "最后的", "late": "晚的", "later": "后来", "laugh": "笑",
    "lay": "放置", "lead": "领导", "leader": "领导者", "learn": "学习",
    "least": "最少", "leave": "离开", "led": "领导", "left": "左边",
    "leg": "腿", "less": "更少", "let": "让", "letter": "信",
    "level": "水平", "lie": "躺", "life": "生活", "lift": "举起",
    "light": "光", "like": "喜欢", "likely": "可能的", "line": "线",
    "list": "列表", "listen": "听", "little": "小的", "live": "生活",
    "local": "当地的", "long": "长的", "look": "看", "lose": "失去",
    "lost": "丢失", "lot": "很多", "love": "爱", "low": "低的",
    "machine": "机器", "made": "制作", "main": "主要的", "major": "主要的",
    "make": "制作", "man": "男人", "many": "很多", "map": "地图",
    "mark": "标记", "market": "市场", "master": "主人", "material": "材料",
    "matter": "事情", "may": "可能", "maybe": "也许", "mean": "意思是",
    "means": "方法", "meant": "意思是", "measure": "测量", "meet": "遇见",
    "meeting": "会议", "member": "成员", "memory": "记忆", "men": "男人们",
    "mention": "提到", "method": "方法", "middle": "中间", "might": "可能",
    "mile": "英里", "military": "军事", "million": "百万", "mind": "头脑",
    "minute": "分钟", "miss": "错过", "model": "模型", "modern": "现代的",
    "moment": "时刻", "money": "钱", "month": "月份", "more": "更多",
    "morning": "早上", "most": "最多的", "mother": "母亲",
    "mountain": "山", "mouth": "嘴", "move": "移动", "movement": "运动",
    "movie": "电影", "much": "很多", "music": "音乐", "must": "必须",
    "myself": "我自己", "name": "名字", "nation": "国家", "national": "国家的",
    "natural": "自然的", "nature": "自然", "near": "近的", "nearly": "几乎",
    "necessary": "必要的", "need": "需要", "neighbor": "邻居",
    "neither": "两者都不", "never": "从不", "new": "新的", "news": "新闻",
    "next": "下一个", "nice": "美好的", "night": "夜晚", "nine": "九",
    "no": "不", "none": "一个也没有", "nor": "也不", "north": "北方",
    "not": "不", "note": "笔记", "nothing": "什么都没有",
    "notice": "注意", "noun": "名词", "now": "现在", "number": "数字",
    "object": "物体", "observe": "观察", "occur": "发生", "ocean": "海洋",
    "of": "...的", "off": "离开", "offer": "提供", "office": "办公室",
    "official": "官员", "often": "经常", "oh": "哦", "oil": "油",
    "ok": "好的", "old": "老的", "on": "在...上", "once": "曾经",
    "one": "一个", "only": "只有", "onto": "到...上", "open": "打开",
    "operation": "手术", "opinion": "意见", "opportunity": "机会",
    "or": "或者", "order": "命令", "organization": "组织",
    "original": "原始的", "other": "其他的", "our": "我们的",
    "ourselves": "我们自己", "out": "外面", "outside": "外面",
    "over": "结束", "own": "自己的", "owner": "所有者", "page": "页",
    "pain": "疼痛", "pair": "一对", "paper": "纸", "parent": "父母",
    "part": "部分", "particular": "特定的", "party": "派对",
    "pass": "通过", "past": "过去", "patient": "病人", "pattern": "模式",
    "pay": "支付", "peace": "和平", "people": "人们", "per": "每",
    "percent": "百分比", "perfect": "完美的", "perform": "表演",
    "performance": "表演", "perhaps": "也许", "period": "时期",
    "person": "人", "personal": "个人的", "phone": "电话",
    "physical": "身体的", "pick": "挑选", "picture": "图片",
    "piece": "片", "place": "地方", "plain": "简单的", "plan": "计划",
    "plant": "植物", "play": "玩", "player": "播放器", "please": "请",
    "point": "点", "police": "警察", "policy": "政策",
    "political": "政治的", "poor": "贫穷的", "popular": "流行的",
    "population": "人口", "position": "位置", "positive": "积极的",
    "possible": "可能的", "power": "力量", "practice": "练习",
    "prepare": "准备", "present": "现在", "president": "总统",
    "press": "按", "price": "价格", "private": "私人的",
    "probably": "可能", "problem": "问题", "process": "过程",
    "produce": "生产", "product": "产品", "production": "生产",
    "professional": "专业的", "professor": "教授", "program": "程序",
    "project": "项目", "property": "财产", "protect": "保护",
    "prove": "证明", "provide": "提供", "public": "公共的",
    "pull": "拉", "purpose": "目的", "put": "放", "quality": "质量",
    "question": "问题", "quick": "快的", "quickly": "快地",
    "quite": "相当", "race": "种族", "radio": "收音机", "raise": "举起",
    "ran": "跑", "range": "范围", "rate": "比率", "rather": "相当",
    "reach": "到达", "read": "阅读", "ready": "准备好的", "real": "真的",
    "reality": "现实", "realize": "意识到", "really": "真的",
    "reason": "原因", "receive": "收到", "recent": "最近的",
    "recently": "最近", "record": "记录", "red": "红色",
    "reduce": "减少", "reflect": "反映", "region": "地区",
    "relate": "相关", "relationship": "关系", "remain": "保持",
    "remember": "记得", "remove": "删除", "repeat": "重复",
    "report": "报告", "represent": "代表", "require": "需要",
    "research": "研究", "resource": "资源", "respond": "回应",
    "response": "回应", "rest": "休息", "result": "结果",
    "return": "返回", "reveal": "揭示", "rich": "富有的",
    "right": "正确的", "rise": "上升", "risk": "风险", "river": "河",
    "road": "路", "rock": "岩石", "role": "角色", "room": "房间",
    "rule": "规则", "run": "跑", "safe": "安全的", "said": "说",
    "sake": "缘故", "sale": "销售", "same": "相同的", "save": "保存",
    "say": "说", "scene": "场景", "school": "学校", "science": "科学",
    "scientist": "科学家", "sea": "海", "search": "搜索",
    "season": "季节", "second": "第二", "section": "部分",
    "security": "安全", "see": "看见", "seek": "寻找", "seem": "似乎",
    "sell": "卖", "send": "发送", "senior": "高级的", "sense": "感觉",
    "series": "系列", "serious": "严肃的", "serve": "服务",
    "service": "服务", "set": "设置", "seven": "七", "several": "几个",
    "shake": "摇动", "share": "分享", "she": "她", "short": "短的",
    "should": "应该", "show": "显示", "side": "边", "sign": "标志",
    "significant": "重要的", "similar": "相似的", "simple": "简单的",
    "simply": "简单地", "since": "自从", "sing": "唱",
    "single": "单一的", "sister": "姐妹", "sit": "坐", "site": "地点",
    "situation": "情况", "six": "六", "size": "大小", "skill": "技能",
    "skin": "皮肤", "small": "小的", "smile": "微笑", "so": "所以",
    "social": "社会的", "society": "社会", "soldier": "士兵",
    "some": "一些", "somebody": "某人", "someone": "某人",
    "something": "某物", "sometimes": "有时", "son": "儿子",
    "song": "歌曲", "soon": "很快", "sort": "种类", "sound": "声音",
    "source": "来源", "south": "南方", "southern": "南方的",
    "space": "空间", "speak": "说话", "special": "特别的",
    "specific": "具体的", "speech": "演讲", "spend": "花费",
    "spirit": "精神", "sport": "运动", "spring": "春天",
    "staff": "员工", "stage": "舞台", "stand": "站立",
    "standard": "标准", "star": "星星", "start": "开始", "state": "状态",
    "station": "车站", "stay": "停留", "step": "步骤", "still": "仍然",
    "stock": "股票", "stone": "石头", "stop": "停止", "store": "商店",
    "story": "故事", "straight": "直的", "strange": "奇怪的",
    "strategy": "策略", "stream": "流", "street": "街道",
    "strike": "罢工", "strong": "强壮的", "structure": "结构",
    "student": "学生", "study": "学习", "stuff": "东西",
    "style": "风格", "subject": "主题", "success": "成功",
    "successful": "成功的", "such": "这样的", "suddenly": "突然",
    "suffer": "遭受", "suggest": "建议", "summer": "夏天",
    "super": "超级的", "supply": "供应", "support": "支持",
    "sure": "肯定的", "surface": "表面", "system": "系统",
    "table": "桌子", "take": "拿", "talk": "谈话", "tax": "税",
    "tea": "茶", "teach": "教", "teacher": "老师", "team": "团队",
    "technology": "技术", "television": "电视", "tell": "告诉",
    "ten": "十", "term": "术语", "test": "测试", "than": "比",
    "thank": "谢谢", "that": "那", "the": "定冠词", "their": "他们的",
    "them": "他们", "themselves": "他们自己", "then": "然后",
    "theory": "理论", "there": "那里", "these": "这些", "they": "他们",
    "thing": "事情", "think": "想", "third": "第三", "this": "这",
    "those": "那些", "though": "虽然", "thought": "想法",
    "thousand": "千", "three": "三", "through": "通过",
    "throughout": "贯穿", "throw": "扔", "thus": "因此",
    "time": "时间", "to": "到", "today": "今天", "together": "一起",
    "told": "告诉", "tomorrow": "明天", "tonight": "今晚",
    "too": "也", "took": "拿", "top": "顶部", "total": "总的",
    "tough": "困难的", "toward": "朝向", "town": "城镇",
    "trade": "贸易", "traditional": "传统的", "training": "培训",
    "travel": "旅行", "treat": "对待", "treatment": "治疗",
    "trial": "审判", "trip": "旅行", "trouble": "麻烦",
    "true": "真实的", "truth": "真相", "try": "尝试", "turn": "转",
    "tv": "电视", "two": "二", "type": "类型", "under": "在...下",
    "understand": "理解", "unit": "单位", "until": "直到",
    "up": "向上", "upon": "在...上", "us": "我们", "use": "使用",
    "usually": "通常", "value": "价值", "various": "各种各样的",
    "very": "非常", "view": "视图", "village": "村庄", "visit": "访问",
    "voice": "声音", "vote": "投票", "wait": "等待", "walk": "走",
    "wall": "墙", "want": "想要", "war": "战争", "watch": "观看",
    "way": "方式", "we": "我们", "weapon": "武器", "wear": "穿",
    "week": "周", "weight": "重量", "well": "好", "west": "西方",
    "western": "西方的", "what": "什么", "whatever": "无论什么",
    "when": "什么时候", "where": "在哪里", "whether": "是否",
    "which": "哪个", "while": "当...时", "white": "白色",
    "who": "谁", "whole": "整个的", "whom": "谁", "whose": "谁的",
    "why": "为什么", "wide": "宽的", "wife": "妻子", "will": "将要",
    "win": "赢", "window": "窗户", "winter": "冬天", "wish": "希望",
    "with": "和", "within": "在...内", "without": "没有",
    "woman": "女人", "wonder": "想知道", "wood": "木头",
    "word": "单词", "work": "工作", "worker": "工人", "world": "世界",
    "worry": "担心", "would": "会", "write": "写", "writer": "作家",
    "wrong": "错误的", "yard": "院子", "yeah": "是的", "year": "年",
    "yes": "是的", "yet": "还", "you": "你", "young": "年轻的",
    "your": "你的", "yourself": "你自己",

    # 更多词汇（~500个补充词）
    "achieve": "实现", "across": "横过", "activity": "活动",
    "actually": "实际上", "address": "地址", "adult": "成年人",
    "advance": "前进", "advantage": "优势", "adventure": "冒险",
    "affect": "影响", "afternoon": "下午", "ahead": "向前",
    "aim": "目标", "allow": "允许", "although": "虽然",
    "angry": "生气的", "announce": "宣布", "anxious": "焦虑的",
    "anyway": "无论如何", "apart": "分开", "apartment": "公寓",
    "apologize": "道歉", "appear": "出现", "apply": "申请",
    "appoint": "任命", "approach": "接近", "approve": "批准",
    "argue": "争论", "arrange": "安排", "arrival": "到达",
    "article": "文章", "aside": "旁边", "assume": "假设",
    "atmosphere": "气氛", "attach": "附上", "attempt": "尝试",
    "attend": "参加", "attention": "注意", "attitude": "态度",
    "attract": "吸引", "audience": "观众", "author": "作者",
    "authority": "权威", "available": "可用的", "average": "平均",
    "avoid": "避免", "award": "奖励", "aware": "意识到",
    "background": "背景", "balance": "平衡", "baseball": "棒球",
    "basic": "基本的", "basket": "篮子", "battle": "战斗",
    "beg": "乞求", "behavior": "行为", "belief": "信念",
    "bell": "铃铛", "belong": "属于", "bench": "长凳",
    "benefit": "好处", "besides": "此外", "beyond": "超出",
    "bicycle": "自行车", "bill": "账单", "billion": "十亿",
    "bind": "绑定", "biology": "生物学", "bit": "一点",
    "bite": "咬", "bitter": "苦的", "blame": "责怪",
    "blank": "空白的", "blind": "盲的", "block": "块",
    "blow": "吹", "bomb": "炸弹", "bond": "债券",
    "boring": "无聊的", "borrow": "借", "boss": "老板",
    "bottle": "瓶子", "brain": "大脑", "brave": "勇敢的",
    "breath": "呼吸", "bridge": "桥", "brief": "简短的",
    "bright": "明亮的", "broadcast": "广播", "broke": "破产的",
    "bubble": "气泡", "bucket": "水桶", "budget": "预算",
    "bunch": "束", "burden": "负担", "button": "按钮",
    "cabin": "小屋", "cabinet": "橱柜", "cable": "电缆",
    "cake": "蛋糕", "calm": "冷静的", "camera": "相机",
    "cancel": "取消", "candle": "蜡烛", "capable": "有能力的",
    "career": "职业", "cargo": "货物", "carpet": "地毯",
    "castle": "城堡", "cattle": "牛群", "cave": "洞穴",
    "ceiling": "天花板", "celebrate": "庆祝", "ceremony": "仪式",
    "chain": "链条", "challenge": "挑战", "champion": "冠军",
    "channel": "频道", "chaos": "混乱", "chapter": "章节",
    "charity": "慈善", "chart": "图表", "chase": "追逐",
    "cheap": "便宜的", "cheat": "作弊", "cheese": "奶酪",
    "chemical": "化学的", "chest": "胸膛", "chief": "首领",
    "chip": "芯片", "chocolate": "巧克力", "choice": "选择",
    "citizen": "公民", "civil": "公民的", "clap": "鼓掌",
    "classic": "经典的", "classroom": "教室", "clay": "黏土",
    "clever": "聪明的", "climate": "气候", "clinic": "诊所",
    "clock": "时钟", "closet": "壁橱", "clue": "线索",
    "clumsy": "笨拙的", "coach": "教练", "coast": "海岸",
    "coin": "硬币", "collar": "衣领", "colleague": "同事",
    "colony": "殖民地", "combine": "结合", "comedy": "喜剧",
    "comfort": "舒适", "command": "命令", "comment": "评论",
    "commit": "犯", "committee": "委员会", "communicate": "交流",
    "community": "社区", "compare": "比较", "compete": "竞争",
    "complain": "抱怨", "complex": "复杂的", "compose": "组成",
    "concentrate": "集中", "concept": "概念", "concern": "关心",
    "conclude": "总结", "concrete": "具体的", "conduct": "行为",
    "conference": "会议", "confident": "自信的", "confirm": "确认",
    "conflict": "冲突", "confuse": "困惑", "connect": "连接",
    "conscious": "有意识的", "consequence": "结果",
    "conservative": "保守的", "consider": "考虑",
    "consistent": "一致的", "constant": "不变的",
    "construct": "建造", "consume": "消费", "contact": "联系",
    "contain": "包含", "contemporary": "当代的",
    "content": "内容", "contest": "比赛", "context": "上下文",
    "contract": "合同", "contrast": "对比", "contribute": "贡献",
    "controversy": "争议", "convenient": "方便的",
    "convention": "惯例", "conversation": "对话",
    "convert": "转换", "convince": "说服", "cookie": "饼干",
    "cope": "应对", "core": "核心", "corporate": "公司的",
    "corridor": "走廊", "council": "委员会", "counselor": "顾问",
    "county": "县", "couple": "夫妻", "courage": "勇气",
    "cousin": "表亲", "crash": "碰撞", "crazy": "疯狂的",
    "cream": "奶油", "creative": "有创意的", "creature": "生物",
    "credit": "信用", "crew": "全体人员", "crime": "犯罪",
    "criminal": "罪犯", "crisis": "危机", "criteria": "标准",
    "critical": "批评的", "crop": "农作物", "crossing": "十字路口",
    "crucial": "关键的", "cultural": "文化的", "culture": "文化",
    "cupboard": "橱柜", "cure": "治愈", "curious": "好奇的",
    "currency": "货币", "curtain": "窗帘", "cushion": "垫子",
    "custom": "习俗", "customer": "顾客", "cycle": "循环",
    "daily": "每日的", "damage": "损害", "danger": "危险",
    "dare": "敢", "database": "数据库", "dawn": "黎明",
    "debate": "辩论", "debt": "债务", "decade": "十年",
    "decent": "体面的", "declare": "宣布", "decline": "下降",
    "decorate": "装饰", "decrease": "减少", "deer": "鹿",
    "defeat": "击败", "defend": "防御", "define": "定义",
    "definite": "明确的", "delay": "延迟", "delicate": "精致的",
    "delicious": "美味的", "delight": "高兴", "deliver": "交付",
    "democracy": "民主", "demonstrate": "展示", "deny": "否认",
    "depart": "离开", "depend": "依赖", "deposit": "存款",
    "depress": "使沮丧", "depth": "深度", "derive": "源自",
    "deserve": "值得", "desire": "渴望", "desk": "书桌",
    "desperate": "绝望的", "despite": "尽管", "destination": "目的地",
    "destroy": "摧毁", "detail": "细节", "detect": "察觉",
    "develop": "发展", "device": "设备", "devote": "奉献",
    "dialogue": "对话", "diamond": "钻石", "diet": "饮食",
    "digital": "数字的", "dignity": "尊严", "dilemma": "困境",
    "dimension": "维度", "dinner": "晚餐", "diplomat": "外交官",
    "direction": "方向", "director": "导演", "dirty": "脏的",
    "disable": "使残废", "disagree": "不同意", "disappear": "消失",
    "discipline": "纪律", "discover": "发现", "disease": "疾病",
    "dismiss": "解散", "display": "展示", "dispute": "争端",
    "distance": "距离", "distinct": "明显的", "distinguish": "区分",
    "distribute": "分配", "district": "地区", "disturb": "打扰",
    "diverse": "多样的", "divide": "分割", "document": "文件",
    "dolphin": "海豚", "domestic": "国内的", "dominate": "支配",
    "donate": "捐赠", "doubt": "怀疑", "downtown": "市中心",
    "dozen": "一打", "draft": "草稿", "dragon": "龙",
    "drama": "戏剧", "dramatic": "戏剧性的", "drastic": "激烈的",
    "drawer": "抽屉", "drill": "钻", "drown": "淹死",
    "drum": "鼓", "drunk": "醉的", "due": "到期的",
    "dump": "倾倒", "dust": "灰尘", "duty": "职责",
    "dynamic": "动态的", "eager": "渴望的", "earn": "赚",
    "earthquake": "地震", "ease": "安逸", "ecology": "生态学",
    "economy": "经济", "editor": "编辑", "educate": "教育",
    "efficient": "高效的", "effort": "努力", "elbow": "肘",
    "elderly": "年长的", "elect": "选举", "elegant": "优雅的",
    "element": "元素", "elephant": "大象", "eliminate": "消除",
    "embrace": "拥抱", "emerge": "出现", "emergency": "紧急情况",
    "emotion": "情感", "emperor": "皇帝", "emphasis": "强调",
    "empire": "帝国", "employ": "雇佣", "empty": "空的",
    "enable": "使能够", "encounter": "遭遇", "encourage": "鼓励",
    "enemy": "敌人", "engage": "从事", "engine": "引擎",
    "engineer": "工程师", "enormous": "巨大的", "ensure": "确保",
    "enterprise": "企业", "entertain": "娱乐", "enthusiasm": "热情",
    "entire": "整个的", "entrance": "入口", "entry": "进入",
    "environment": "环境", "episode": "集", "equipment": "设备",
    "era": "时代", "error": "错误", "essay": "散文",
    "essential": "必要的", "establish": "建立", "estate": "地产",
    "estimate": "估计", "evaluate": "评估", "evening": "傍晚",
    "eventually": "最终", "evidence": "证据", "evil": "邪恶的",
    "evolution": "进化", "exact": "精确的", "examine": "检查",
    "example": "例子", "exceed": "超过", "excellent": "优秀的",
    "exception": "例外", "exchange": "交换", "excite": "使兴奋",
    "exclude": "排除", "execute": "执行", "exhibit": "展览",
    "expand": "扩展", "expense": "费用", "expensive": "昂贵的",
    "expert": "专家", "explain": "解释", "explode": "爆炸",
    "explore": "探索", "export": "出口", "expose": "暴露",
    "extend": "延伸", "extent": "程度", "external": "外部的",
    "extra": "额外的", "extreme": "极端的", "fabric": "织物",
    "facility": "设施", "factor": "因素", "factory": "工厂",
    "faculty": "能力", "fade": "褪色", "fail": "失败",
    "fairly": "公平地", "faith": "信仰", "false": "假的",
    "familiar": "熟悉的", "fantasy": "幻想", "fashion": "时尚",
    "fat": "胖的", "fatal": "致命的", "fate": "命运",
    "fault": "过错", "favor": "好感", "feather": "羽毛",
    "feature": "特征", "federal": "联邦的", "female": "女性的",
    "fence": "篱笆", "festival": "节日", "fever": "发烧",
    "fiction": "小说", "fierce": "凶猛的", "fifteen": "十五",
    "fighter": "战士", "finance": "财务", "finding": "发现",
    "firm": "坚定的", "fix": "修理", "flame": "火焰",
    "flash": "闪烁", "flat": "平坦的", "flee": "逃离",
    "flesh": "肉", "flexible": "灵活的", "flight": "航班",
    "float": "漂浮", "flood": "洪水", "flour": "面粉",
    "fluent": "流利的", "fluid": "流体", "focus": "焦点",
    "folk": "民间的", "fond": "喜欢的", "fool": "傻瓜",
    "forbid": "禁止", "forecast": "预测", "foreign": "外国的",
    "forever": "永远", "formal": "正式的", "formula": "公式",
    "forth": "向前", "fortune": "财富", "forum": "论坛",
    "forward": "向前", "fossil": "化石", "foundation": "基础",
    "fountain": "喷泉", "fraction": "分数", "fragile": "脆弱的",
    "framework": "框架", "freedom": "自由", "freeze": "冻结",
    "freight": "货运", "frequency": "频率", "friction": "摩擦",
    "frog": "青蛙", "frost": "霜", "frozen": "冷冻的",
    "fuel": "燃料", "fulfill": "实现", "function": "功能",
    "fund": "基金", "fundamental": "基本的", "funeral": "葬礼",
    "fur": "皮毛", "furniture": "家具", "furthermore": "此外",
    "gain": "获得", "gallery": "画廊", "gap": "缺口",
    "garage": "车库", "garbage": "垃圾", "garden": "花园",
    "garlic": "大蒜", "gas": "气体", "gate": "大门",
    "gather": "聚集", "gauge": "测量", "gaze": "凝视",
    "gear": "齿轮", "gender": "性别", "gene": "基因",
    "generous": "慷慨的", "genius": "天才", "gentle": "温柔的",
    "genuine": "真正的", "geography": "地理", "gesture": "手势",
    "giant": "巨大的", "gift": "礼物", "giraffe": "长颈鹿",
    "glance": "一瞥", "globe": "地球仪", "glory": "荣耀",
    "glove": "手套", "glow": "发光", "glue": "胶水",
    "governor": "州长", "grab": "抓取", "grace": "优雅",
    "gradual": "逐渐的", "grain": "谷物", "grammar": "语法",
    "grandfather": "祖父", "grandmother": "祖母", "grant": "授予",
    "grape": "葡萄", "graph": "图表", "grasp": "抓住",
    "grateful": "感激的", "grave": "坟墓", "gravity": "重力",
    "greedy": "贪婪的", "greet": "问候", "grief": "悲伤",
    "grill": "烤架", "grin": "露齿笑", "grip": "紧握",
    "grocery": "杂货店", "gross": "总的", "guarantee": "保证",
    "guard": "守卫", "guilty": "有罪的", "guitar": "吉他",
    "gulf": "海湾", "gum": "口香糖", "gun": "枪",
    "guy": "家伙", "gym": "体育馆", "habit": "习惯",
    "habitat": "栖息地", "hail": "冰雹", "ham": "火腿",
    "hammer": "锤子", "handful": "一把", "handle": "处理",
    "handsome": "英俊的", "handwriting": "笔迹", "handy": "方便的",
    "harbor": "港口", "harden": "变硬", "hardly": "几乎不",
    "hardware": "硬件", "harm": "伤害", "harmony": "和谐",
    "harvest": "收获", "hatred": "仇恨", "haunt": "萦绕",
    "headline": "头条", "headquarters": "总部", "heal": "治愈",
    "heap": "堆", "heaven": "天堂", "hedge": "树篱",
    "heel": "脚后跟", "height": "高度", "helmet": "头盔",
    "herb": "草药", "herd": "牧群", "heritage": "遗产",
    "hero": "英雄", "hide": "躲藏", "highlight": "强调",
    "highway": "高速公路", "hike": "远足", "hint": "提示",
    "hip": "臀部", "hire": "雇佣", "hobby": "爱好",
    "honest": "诚实的", "honey": "蜂蜜", "honor": "荣誉",
    "hook": "钩子", "hop": "跳跃", "horizon": "地平线",
    "horn": "角", "horror": "恐怖", "host": "主人",
    "hostile": "敌对的", "household": "家庭", "housing": "住房",
    "hug": "拥抱", "humor": "幽默", "hunt": "打猎",
    "hurricane": "飓风", "hurry": "匆忙", "hurt": "伤害",
    "hydrogen": "氢", "icon": "图标", "identical": "相同的",
    "identity": "身份", "ignore": "忽视", "illegal": "非法的",
    "illness": "疾病", "illustrate": "说明", "immediate": "立即的",
    "immense": "巨大的", "immigrant": "移民", "immune": "免疫的",
    "implement": "实施", "imply": "暗示", "import": "进口",
    "impose": "强加", "impress": "使印象深刻", "impulse": "冲动",
    "incident": "事件", "incline": "倾斜", "income": "收入",
    "increase": "增加", "incredible": "难以置信的", "independence": "独立",
    "independent": "独立的", "index": "索引", "individual": "个人的",
    "infant": "婴儿", "influence": "影响", "inform": "通知",
    "initial": "最初的", "injury": "伤害", "innocent": "无辜的",
    "innovation": "创新", "input": "输入", "inquiry": "询问",
    "insect": "昆虫", "insert": "插入", "insist": "坚持",
    "inspect": "检查", "install": "安装", "instance": "实例",
    "instant": "立即的", "institute": "学院", "institution": "机构",
    "instrument": "工具", "insurance": "保险", "intellectual": "智力的",
    "intelligence": "智力", "intend": "打算", "intense": "强烈的",
    "intention": "意图", "interact": "互动", "internal": "内部的",
    "interpret": "解释", "interrupt": "打断", "interval": "间隔",
    "intervention": "干预", "intimate": "亲密的", "introduce": "介绍",
    "invade": "入侵", "invent": "发明", "invest": "投资",
    "investigate": "调查", "invite": "邀请", "involve": "涉及",
    "iron": "铁", "isolate": "隔离", "jail": "监狱",
    "jam": "果酱", "jealous": "嫉妒的", "jeans": "牛仔裤",
    "jet": "喷气机", "jewelry": "珠宝", "joint": "关节",
    "joke": "笑话", "journal": "日记", "journalist": "记者",
    "journey": "旅程", "joy": "喜悦", "judge": "法官",
    "judgment": "判断", "juice": "果汁", "jungle": "丛林",
    "junior": "初级的", "jury": "陪审团", "justice": "正义",
    "keen": "热衷的", "kettle": "水壶", "keyboard": "键盘",
    "kick": "踢", "kid": "孩子", "kidney": "肾脏",
    "kindness": "善良", "kiss": "吻", "knee": "膝盖",
    "knife": "刀", "knock": "敲", "knot": "结",
    "label": "标签", "labor": "劳动", "laboratory": "实验室",
    "lack": "缺乏", "ladder": "梯子", "lamp": "灯",
    "landmark": "地标", "landscape": "风景", "lane": "小巷",
    "lap": "膝盖", "laser": "激光", "latter": "后者",
    "launch": "发射", "laundry": "洗衣房", "lavender": "薰衣草",
    "law": "法律", "lawn": "草坪", "lawsuit": "诉讼",
    "layer": "层", "layout": "布局", "league": "联盟",
    "leather": "皮革", "lecture": "讲座", "legal": "法律的",
    "legend": "传说", "legislation": "立法", "leisure": "休闲",
    "lemon": "柠檬", "lend": "借出", "length": "长度",
    "lens": "镜头", "lesson": "课程", "liberal": "自由的",
    "liberty": "自由", "library": "图书馆", "license": "执照",
    "lid": "盖子", "lifetime": "终生", "limb": "肢体",
    "limit": "限制", "limp": "跛行", "link": "链接",
    "liquid": "液体", "literacy": "读写能力", "literary": "文学的",
    "literature": "文学", "liver": "肝脏", "living": "生活",
    "load": "负载", "loan": "贷款", "lobby": "大厅",
    "lodge": "小屋", "log": "原木", "logic": "逻辑",
    "lonely": "孤独的", "loose": "松的", "lord": "领主",
    "lorry": "卡车", "loud": "大声的", "lounge": "休息室",
    "loyal": "忠诚的", "luck": "运气", "luggage": "行李",
    "lump": "块", "lung": "肺", "luxury": "奢侈",
    "machinery": "机械", "magazine": "杂志", "magic": "魔法",
    "magnet": "磁铁", "magnificent": "壮丽的", "maid": "女仆",
    "maintain": "维持", "majority": "多数", "maker": "制造者",
    "mall": "商场", "management": "管理", "manner": "方式",
    "manufacture": "制造", "margin": "边缘", "marine": "海洋的",
    "marriage": "婚姻", "married": "已婚的", "mask": "面具",
    "mass": "质量", "massive": "大量的", "mate": "伙伴",
    "maximum": "最大值", "mayor": "市长", "meal": "餐",
    "meaning": "意义", "meanwhile": "同时", "meat": "肉",
    "medal": "奖牌", "media": "媒体", "medical": "医学的",
    "medium": "中等", "melon": "瓜", "melt": "融化",
    "memo": "备忘录", "memorial": "纪念的", "mental": "精神的",
    "menu": "菜单", "merchant": "商人", "mercy": "仁慈",
    "mere": "仅仅的", "merely": "仅仅", "merger": "合并",
    "merit": "优点", "mess": "混乱", "message": "消息",
    "metal": "金属", "metaphor": "隐喻", "meter": "米",
    "midnight": "午夜", "mild": "温和的", "militant": "好战的",
    "mill": "磨坊", "mineral": "矿物", "minimal": "最小的",
    "minimum": "最小值", "minister": "部长", "ministry": "部门",
    "minor": "较小的", "minority": "少数", "miracle": "奇迹",
    "mirror": "镜子", "miserable": "悲惨的", "misleading": "误导的",
    "missile": "导弹", "missing": "失踪的", "mission": "任务",
    "mist": "薄雾", "mistake": "错误", "mix": "混合",
    "mixture": "混合物", "mobile": "移动的", "moderate": "适度的",
    "modest": "谦虚的", "modify": "修改", "moisture": "水分",
    "molecule": "分子", "monitor": "监控", "monk": "和尚",
    "monkey": "猴子", "monopoly": "垄断", "mood": "心情",
    "moral": "道德的", "moreover": "此外", "mosquito": "蚊子",
    "motion": "运动", "motivate": "激励", "motor": "马达",
    "motto": "座右铭", "mould": "模具", "mount": "登上",
    "mouse": "老鼠", "mud": "泥", "multiple": "多个的",
    "multiply": "乘", "municipal": "市政的", "murder": "谋杀",
    "murmur": "低语", "muscle": "肌肉", "museum": "博物馆",
    "mushroom": "蘑菇", "musician": "音乐家", "mutual": "相互的",
    "mysterious": "神秘的", "mystery": "神秘", "myth": "神话",
    "nail": "指甲", "naked": "裸体的", "narrow": "狭窄的",
    "nasty": "肮脏的", "native": "本地的", "navy": "海军",
    "neat": "整洁的", "necessarily": "必然地", "negative": "消极的",
    "neglect": "忽视", "negotiate": "谈判", "nerve": "神经",
    "network": "网络", "neutral": "中立的", "nevertheless": "然而",
    "nickname": "绰号", "noble": "高贵的", "nod": "点头",
    "noise": "噪音", "nominate": "提名", "nonetheless": "尽管如此",
    "nonsense": "胡说", "normal": "正常的", "normally": "正常地",
    "northern": "北方的", "nostril": "鼻孔", "notebook": "笔记本",
    "notion": "概念", "novel": "小说", "nowhere": "无处",
    "nuclear": "核的", "nuisance": "讨厌的人或事", "numerous": "许多的",
    "nurse": "护士", "nursery": "托儿所", "nut": "坚果",
    "nutrition": "营养", "nylon": "尼龙",
    "oak": "橡树", "obey": "服从", "objective": "客观的",
    "obligation": "义务", "obtain": "获得", "obvious": "明显的",
    "occasion": "场合", "occupation": "职业", "occupy": "占据",
    "odd": "奇怪的", "offend": "冒犯", "offense": "冒犯",
    "officer": "官员", "ongoing": "进行中的", "online": "在线的",
    "opening": "开口", "operate": "操作", "operator": "操作员",
    "opponent": "对手", "oppose": "反对", "opposite": "相反的",
    "option": "选项", "orbit": "轨道", "orchestra": "管弦乐队",
    "organ": "器官", "organic": "有机的", "organism": "有机体",
    "orientation": "方向", "origin": "起源", "otherwise": "否则",
    "ounce": "盎司", "outcome": "结果", "outlet": "出口",
    "outline": "大纲", "output": "输出", "outrage": "愤怒",
    "outstanding": "杰出的", "oval": "椭圆形的", "oven": "烤箱",
    "overall": "整体的", "overcome": "克服", "overlook": "忽视",
    "overnight": "过夜", "overseas": "海外的", "owe": "欠",
    "owl": "猫头鹰", "oxygen": "氧气",
    "pace": "步伐", "pack": "包装", "package": "包裹",
    "pad": "垫子", "palm": "手掌", "panel": "面板",
    "panic": "恐慌", "pants": "裤子", "paradise": "天堂",
    "paragraph": "段落", "parallel": "平行的", "parameter": "参数",
    "parcel": "包裹", "parliament": "议会", "partial": "部分的",
    "participate": "参与", "particle": "粒子", "passage": "通道",
    "passenger": "乘客", "passion": "热情", "passive": "被动的",
    "passport": "护照", "password": "密码", "pasta": "意大利面",
    "paste": "粘贴", "patch": "补丁", "patent": "专利",
    "path": "路径", "patience": "耐心", "patrol": "巡逻",
    "pause": "暂停", "pavement": "人行道", "payment": "付款",
    "peak": "高峰", "peanut": "花生", "pearl": "珍珠",
    "peasant": "农民", "peel": "剥皮", "penalty": "惩罚",
    "pencil": "铅笔", "penny": "便士", "pension": "养老金",
    "pepper": "胡椒", "perceive": "感知", "permanent": "永久的",
    "permission": "许可", "persist": "坚持", "personality": "个性",
    "personnel": "人员", "perspective": "观点", "persuade": "说服",
    "phase": "阶段", "phenomenon": "现象", "philosophy": "哲学",
    "photo": "照片", "phrase": "短语", "physician": "内科医生",
    "piano": "钢琴", "pie": "馅饼", "pierce": "刺穿",
    "pigeon": "鸽子", "pill": "药丸", "pillow": "枕头",
    "pilot": "飞行员", "pine": "松树", "pink": "粉色的",
    "pipeline": "管道", "pirate": "海盗", "pistol": "手枪",
    "pit": "坑", "pitch": "投掷", "pizza": "比萨",
    "planet": "行星", "plastic": "塑料", "platform": "平台",
    "plausible": "看似合理的", "plead": "恳求", "pledge": "誓言",
    "plenty": "丰富", "plot": "情节", "plug": "插头",
    "plunge": "跳入", "plural": "复数", "pocket": "口袋",
    "poem": "诗", "poet": "诗人", "poetry": "诗歌",
    "poison": "毒药", "pole": "杆", "polish": "抛光",
    "poll": "民意调查", "pollution": "污染", "pond": "池塘",
    "pool": "水池", "pop": "流行", "port": "港口",
    "portable": "便携的", "portfolio": "投资组合", "portion": "部分",
    "portrait": "肖像", "pose": "姿势", "possess": "拥有",
    "possibility": "可能性", "postpone": "推迟", "pot": "锅",
    "potential": "潜力", "potato": "土豆", "pound": "磅",
    "pour": "倒", "poverty": "贫穷", "powder": "粉末",
    "pray": "祈祷", "prayer": "祈祷", "preach": "布道",
    "precede": "先于", "precious": "珍贵的", "precise": "精确的",
    "predict": "预测", "prefer": "更喜欢", "pregnant": "怀孕的",
    "prejudice": "偏见", "preliminary": "初步的", "premise": "前提",
    "premium": "保费", "preparation": "准备", "prescribe": "开药",
    "preservation": "保存", "preserve": "保存", "presidency": "总统任期",
    "presidential": "总统的", "presume": "假设", "pretend": "假装",
    "prevail": "获胜", "prevent": "防止", "previous": "以前的",
    "prey": "猎物", "priest": "牧师", "primary": "主要的",
    "prime": "主要的", "primitive": "原始的", "prince": "王子",
    "princess": "公主", "principal": "主要的", "principle": "原则",
    "print": "打印", "prior": "优先的", "priority": "优先",
    "prison": "监狱", "prisoner": "囚犯", "privacy": "隐私",
    "privilege": "特权", "prize": "奖品", "probe": "探测",
    "proceed": "继续", "proceedings": "诉讼", "processor": "处理器",
    "proclaim": "宣布", "produce": "生产", "profession": "职业",
    "profile": "轮廓", "profit": "利润", "profound": "深刻的",
    "progressive": "进步的", "prohibit": "禁止", "prominent": "突出的",
    "promise": "承诺", "promote": "促进", "prompt": "迅速的",
    "pronounce": "发音", "proof": "证据", "propaganda": "宣传",
    "proper": "适当的", "proportion": "比例", "proposal": "提议",
    "propose": "提议", "prosecutor": "检察官", "prospect": "前景",
    "protect": "保护", "protein": "蛋白质", "protest": "抗议",
    "protocol": "协议", "proud": "自豪的", "prove": "证明",
    "provision": "供应", "provoke": "挑衅", "psychology": "心理学",
    "pub": "酒馆", "publish": "出版", "pulse": "脉搏",
    "pump": "泵", "punch": "打", "punctual": "准时的",
    "punish": "惩罚", "pupil": "学生", "purchase": "购买",
    "pure": "纯的", "purple": "紫色的", "pursue": "追求",
    "puzzle": "谜题", "pyramid": "金字塔",
    "qualify": "有资格", "quantity": "数量", "quarter": "四分之一",
    "queen": "女王", "quest": "探索", "queue": "队列",
    "quit": "放弃", "quiz": "小测验", "quote": "引用",
    "rabbit": "兔子", "racial": "种族的", "rack": "架子",
    "radar": "雷达", "radiation": "辐射", "radical": "激进的",
    "rag": "破布", "rage": "愤怒", "raid": "突袭",
    "rail": "铁轨", "railroad": "铁路", "rainbow": "彩虹",
    "rally": "集会", "random": "随机的", "rank": "等级",
    "rape": "强奸", "rapid": "迅速的", "rare": "稀有的",
    "rat": "老鼠", "ratio": "比率", "rational": "理性的",
    "raw": "生的", "ray": "光线", "react": "反应",
    "reaction": "反应", "reader": "读者", "reading": "阅读",
    "realm": "领域", "rear": "后部", "rebel": "反叛者",
    "rebellion": "叛乱", "reception": "接待", "recession": "衰退",
    "recipe": "食谱", "reckon": "估计", "recognition": "认可",
    "recommend": "推荐", "reconstruction": "重建", "recover": "恢复",
    "recreation": "娱乐", "recruit": "招募", "recycle": "回收",
    "redirect": "重定向", "reduction": "减少", "refer": "参考",
    "reference": "参考", "reform": "改革", "refuge": "避难",
    "refugee": "难民", "refuse": "拒绝", "regard": "认为",
    "regardless": "不管", "regime": "政权", "register": "注册",
    "regulate": "调节", "regulation": "规则", "rehab": "康复",
    "reinforce": "加强", "reject": "拒绝", "relate": "相关",
    "relation": "关系", "relative": "相对的", "release": "释放",
    "relevant": "相关的", "relief": "救济", "religion": "宗教",
    "religious": "宗教的", "reluctant": "不情愿的", "rely": "依赖",
    "remain": "保持", "remark": "评论", "remedy": "补救",
    "remote": "遥远的", "remove": "移除", "render": "提供",
    "renew": "更新", "rent": "租", "repair": "修理",
    "repay": "偿还", "repeat": "重复", "replace": "取代",
    "reply": "回复", "representative": "代表", "reproduce": "繁殖",
    "republic": "共和国", "reputation": "声誉", "request": "请求",
    "rescue": "营救", "resemble": "像", "reservation": "预订",
    "reserve": "保留", "reside": "居住", "residence": "住宅",
    "resident": "居民", "resign": "辞职", "resist": "抵抗",
    "resolution": "决心", "resolve": "解决", "resort": "度假地",
    "respect": "尊重", "respective": "各自的", "respond": "回应",
    "responsible": "负责的", "restore": "恢复", "restrain": "克制",
    "restrict": "限制", "retail": "零售", "retain": "保留",
    "retire": "退休", "retreat": "撤退", "reveal": "揭示",
    "revenue": "收入", "reverse": "相反的", "review": "复习",
    "revise": "修订", "revolution": "革命", "reward": "奖励",
    "rhythm": "节奏", "rib": "肋骨", "ribbon": "丝带",
    "rice": "米饭", "rid": "摆脱", "ride": "骑",
    "ridge": "山脊", "ridiculous": "荒谬的", "rifle": "步枪",
    "rigid": "僵硬的", "ring": "戒指", "riot": "暴动",
    "rip": "撕", "ripe": "成熟的", "ritual": "仪式",
    "rival": "对手", "roar": "咆哮", "roast": "烤",
    "rob": "抢劫", "robbery": "抢劫", "robe": "长袍",
    "robot": "机器人", "robust": "强健的", "rocket": "火箭",
    "rod": "杆", "roll": "滚动", "romance": "浪漫",
    "romantic": "浪漫的", "roof": "屋顶", "rookie": "新手",
    "rope": "绳子", "rotate": "旋转", "rough": "粗糙的",
    "route": "路线", "routine": "常规", "row": "行",
    "royal": "皇家的", "rub": "擦", "rubber": "橡胶",
    "rug": "地毯", "ruin": "毁灭", "ruler": "统治者",
    "rumor": "谣言", "rural": "农村的", "rush": "匆忙",
    "rust": "生锈", "sack": "袋子", "sacred": "神圣的",
    "sacrifice": "牺牲", "saddle": "鞍", "sail": "航行",
    "sailor": "水手", "salad": "沙拉", "salary": "薪水",
    "salmon": "三文鱼", "salt": "盐", "sample": "样品",
    "sanction": "制裁", "satellite": "卫星", "satisfy": "满足",
    "sauce": "酱汁", "sausage": "香肠", "scale": "规模",
    "scan": "扫描", "scandal": "丑闻", "scar": "疤痕",
    "scatter": "分散", "scenario": "情景", "schedule": "时间表",
    "scheme": "方案", "scholar": "学者", "scholarship": "奖学金",
    "scissors": "剪刀", "scope": "范围", "score": "分数",
    "scout": "侦察兵", "scramble": "攀登", "scratch": "抓",
    "scream": "尖叫", "screen": "屏幕", "screw": "螺丝",
    "script": "脚本", "scroll": "滚动", "seal": "密封",
    "seam": "接缝", "secular": "世俗的", "secure": "安全的",
    "segment": "部分", "seize": "抓住", "select": "选择",
    "senator": "参议员", "sensitive": "敏感的", "sentence": "句子",
    "sentiment": "情感", "separate": "分开的", "sequence": "序列",
    "session": "会议", "settle": "解决", "settlement": "定居点",
    "severe": "严重的", "sew": "缝纫", "sex": "性别",
    "sexual": "性的", "shade": "阴影", "shadow": "影子",
    "shaft": "轴", "shallow": "浅的", "shame": "羞耻",
    "shape": "形状", "shark": "鲨鱼", "shelf": "架子",
    "shell": "壳", "shelter": "庇护所", "shield": "盾牌",
    "shift": "转变", "shine": "闪耀", "ship": "船",
    "shirt": "衬衫", "shock": "震惊", "shoe": "鞋",
    "shoot": "射击", "shore": "岸边", "shortage": "短缺",
    "shot": "射击", "shout": "喊叫", "shove": "推",
    "shower": "淋浴", "shrimp": "虾", "shrink": "收缩",
    "shrug": "耸肩", "shut": "关闭", "shuttle": "穿梭",
    "sick": "生病的", "sigh": "叹息", "sight": "视力",
    "signal": "信号", "silence": "沉默", "silent": "沉默的",
    "silk": "丝绸", "silly": "愚蠢的", "silver": "银",
    "sin": "罪", "sincere": "真诚的", "sink": "下沉",
    "sip": "啜饮", "sir": "先生", "ski": "滑雪",
    "sketch": "素描", "skiing": "滑雪", "skilled": "熟练的",
    "skip": "跳过", "skirt": "裙子", "skull": "头骨",
    "slave": "奴隶", "sleep": "睡觉", "slice": "切片",
    "slide": "滑动", "slight": "轻微的", "slip": "滑倒",
    "slogan": "标语", "slope": "斜坡", "slot": "槽",
    "smart": "聪明的", "smell": "气味", "smoke": "烟",
    "snack": "小吃", "snake": "蛇", "snap": "折断",
    "snow": "雪", "soak": "浸泡", "soap": "肥皂",
    "soar": "翱翔", "soccer": "足球", "sock": "袜子",
    "soda": "苏打水", "sodium": "钠", "sofa": "沙发",
    "soft": "柔软的", "software": "软件", "soil": "土壤",
    "solar": "太阳的", "sole": "唯一的", "solemn": "庄严的",
    "solid": "固体的", "solution": "溶液", "solve": "解决",
    "somehow": "以某种方式", "somewhat": "有点儿",
    "sophisticated": "复杂的", "sore": "疼痛的",
    "soul": "灵魂", "soup": "汤", "sour": "酸的",
    "sovereign": "主权的", "sow": "播种", "soy": "大豆",
    "spade": "铲子", "span": "跨度", "spare": "多余的",
    "spark": "火花", "spatial": "空间的", "speaker": "演讲者",
    "spear": "矛", "specialist": "专家", "species": "物种",
    "specific": "具体的", "specify": "指定", "specimen": "标本",
    "spectrum": "光谱", "speculate": "推测", "sphere": "球体",
    "spider": "蜘蛛", "spill": "溢出", "spin": "旋转",
    "spine": "脊柱", "spiral": "螺旋", "spite": "恶意",
    "splash": "溅", "split": "分裂", "spoil": "宠坏",
    "spokesman": "发言人", "sponge": "海绵", "sponsor": "赞助",
    "spoon": "勺子", "spot": "斑点", "spouse": "配偶",
    "spray": "喷雾", "spread": "传播", "spy": "间谍",
    "squad": "小队", "squeeze": "挤压", "stability": "稳定",
    "stable": "稳定的", "stadium": "体育场", "stain": "污点",
    "stair": "楼梯", "stake": "赌注", "stale": "不新鲜的",
    "stall": "摊位", "stamp": "邮票", "stare": "凝视",
    "stark": "鲜明的", "starve": "挨饿", "statue": "雕像",
    "status": "地位", "statute": "法规", "steady": "稳定的",
    "steal": "偷", "steam": "蒸汽", "steel": "钢",
    "steep": "陡峭的", "steer": "驾驶", "stem": "茎",
    "stereotype": "刻板印象", "stern": "严厉的", "stick": "棍子",
    "sticky": "粘的", "stiff": "僵硬的", "stimulus": "刺激",
    "stir": "搅拌", "stitch": "针脚", "stocking": "长袜",
    "stomach": "胃", "stool": "凳子", "stoop": "弯腰",
    "storage": "存储", "storm": "暴风雨", "stove": "炉子",
    "strain": "压力", "strand": "股", "strap": "带子",
    "stranger": "陌生人", "straw": "稻草", "strawberry": "草莓",
    "streak": "条纹", "stream": "流", "strength": "力量",
    "stress": "压力", "stretch": "伸展", "strict": "严格的",
    "stride": "大步走", "strife": "冲突", "string": "绳子",
    "strip": "条", "stripe": "条纹", "stroke": "中风",
    "struggle": "挣扎", "studio": "工作室", "stuff": "东西",
    "stumble": "绊倒", "stun": "使震惊", "stupid": "愚蠢的",
    "sturdy": "结实的", "subdue": "征服", "subject": "主题",
    "submit": "提交", "subsequent": "随后的", "subsidy": "补贴",
    "substance": "物质", "substantial": "大量的", "substitute": "替代品",
    "subtle": "微妙的", "suburb": "郊区", "subway": "地铁",
    "suck": "吸", "sudden": "突然的", "sue": "起诉",
    "suffer": "遭受", "sufficient": "足够的", "sugar": "糖",
    "suit": "套装", "suite": "套房", "sulfur": "硫",
    "sum": "总和", "summary": "摘要", "summit": "峰会",
    "sunlight": "阳光", "sunrise": "日出", "sunset": "日落",
    "sunshine": "阳光", "superb": "极好的", "superior": "优越的",
    "supermarket": "超市", "supervise": "监督", "supplement": "补充",
    "supreme": "最高的", "surge": "激增", "surgeon": "外科医生",
    "surgery": "手术", "surname": "姓氏", "surplus": "过剩",
    "surprise": "惊讶", "surrender": "投降", "surround": "包围",
    "survey": "调查", "survival": "生存", "survive": "幸存",
    "suspect": "怀疑", "suspend": "暂停", "suspicion": "怀疑",
    "sustain": "维持", "swallow": "燕子", "swamp": "沼泽",
    "swap": "交换", "swear": "发誓", "sweat": "汗水",
    "sweater": "毛衣", "sweep": "打扫", "swell": "肿胀",
    "swift": "迅速的", "swim": "游泳", "swing": "摇摆",
    "switch": "开关", "sword": "剑", "symbol": "象征",
    "sympathy": "同情", "symptom": "症状", "syndrome": "综合症",
    "synthetic": "合成的", "syrup": "糖浆",
    "tackle": "处理", "tactic": "战术", "tag": "标签",
    "tail": "尾巴", "tale": "故事", "talent": "才能",
    "tank": "坦克", "tap": "水龙头", "tape": "胶带",
    "target": "目标", "tariff": "关税", "task": "任务",
    "taste": "味道", "tattoo": "纹身", "taxi": "出租车",
    "temple": "寺庙", "temporary": "暂时的", "tempt": "诱惑",
    "tenant": "租户", "tendency": "趋势", "tender": "温柔的",
    "tennis": "网球", "tension": "紧张", "tent": "帐篷",
    "terminal": "终端", "terrace": "露台", "terrain": "地形",
    "terrible": "可怕的", "terrific": "极好的", "territory": "领土",
    "terror": "恐怖", "textile": "纺织品", "texture": "质地",
    "theme": "主题", "therapist": "治疗师", "therapy": "治疗",
    "thick": "厚的", "thief": "小偷", "thigh": "大腿",
    "thin": "薄的", "thirst": "口渴", "thorn": "刺",
    "thread": "线", "threat": "威胁", "threaten": "威胁",
    "threshold": "门槛", "thrill": "兴奋", "throat": "喉咙",
    "throne": "王座", "thrust": "刺", "thumb": "拇指",
    "thunder": "雷", "ticket": "票", "tide": "潮汐",
    "tidy": "整洁的", "tie": "系", "tiger": "老虎",
    "tight": "紧的", "timber": "木材", "tissue": "组织",
    "title": "标题", "toast": "烤面包", "tobacco": "烟草",
    "toe": "脚趾", "toilet": "厕所", "tolerance": "容忍",
    "toll": "通行费", "tomato": "番茄", "tone": "语气",
    "tongue": "舌头", "tool": "工具", "tooth": "牙齿",
    "torch": "火炬", "torture": "折磨", "toss": "扔",
    "touch": "触摸", "tour": "旅游", "tourist": "游客",
    "tournament": "锦标赛", "towel": "毛巾", "tower": "塔",
    "toxic": "有毒的", "trace": "追踪", "track": "轨道",
    "tractor": "拖拉机", "tragedy": "悲剧", "trail": "小径",
    "trait": "特征", "transaction": "交易", "transform": "转变",
    "transit": "运输", "transition": "过渡", "translate": "翻译",
    "transmission": "传输", "transparent": "透明的", "transport": "运输",
    "trap": "陷阱", "trash": "垃圾", "trauma": "创伤",
    "treasure": "宝藏", "treaty": "条约", "tremble": "颤抖",
    "tremendous": "巨大的", "trend": "趋势", "triangle": "三角形",
    "tribe": "部落", "trick": "把戏", "trigger": "触发",
    "trim": "修剪", "triumph": "胜利", "troop": "部队",
    "trophy": "奖杯", "tropical": "热带的", "trunk": "树干",
    "trust": "信任", "tube": "管子", "tuck": "塞入",
    "tug": "拖", "tuition": "学费", "tumble": "摔倒",
    "tune": "曲调", "tunnel": "隧道", "turkey": "火鸡",
    "turtle": "海龟", "tutor": "导师", "twin": "双胞胎",
    "twist": "扭转", "ugly": "丑陋的", "ultimate": "最终的",
    "umbrella": "雨伞", "uncle": "叔叔", "underlying": "潜在的",
    "undermine": "削弱", "undertake": "承担", "unemployment": "失业",
    "unfold": "展开", "uniform": "制服", "union": "联盟",
    "unique": "独特的", "unity": "团结", "universal": "普遍的",
    "universe": "宇宙", "university": "大学", "unknown": "未知的",
    "unless": "除非", "unlike": "不像", "unlikely": "不太可能的",
    "unusual": "不寻常的", "update": "更新", "upgrade": "升级",
    "uphold": "支持", "upper": "上方的", "upright": "直立的",
    "upset": "沮丧的", "urban": "城市的", "urge": "敦促",
    "urgent": "紧急的", "usage": "用法", "utility": "公用设施",
    "utilize": "利用", "utmost": "极度的", "utter": "完全的",
    "vacant": "空着的", "vacation": "假期", "vague": "模糊的",
    "valid": "有效的", "valley": "山谷", "valuable": "有价值的",
    "van": "货车", "vanish": "消失", "variable": "可变的",
    "variation": "变化", "vast": "广阔的", "vegetable": "蔬菜",
    "vehicle": "车辆", "venture": "冒险", "venue": "场地",
    "verify": "验证", "verse": "诗句", "version": "版本",
    "vessel": "容器", "veteran": "老兵", "viable": "可行的",
    "vibrant": "充满活力的", "vice": "邪恶", "victim": "受害者",
    "victory": "胜利", "video": "视频", "vigorous": "有力的",
    "violate": "违反", "violence": "暴力", "violent": "暴力的",
    "virtual": "虚拟的", "virtue": "美德", "virus": "病毒",
    "visible": "可见的", "vision": "愿景", "visual": "视觉的",
    "vital": "至关重要的", "vivid": "生动的", "vocabulary": "词汇",
    "volcano": "火山", "volume": "音量", "voluntary": "自愿的",
    "vulnerable": "脆弱的",
    "wage": "工资", "wagon": "马车", "waist": "腰",
    "wake": "醒来", "wallet": "钱包", "wander": "闲逛",
    "warm": "温暖的", "warn": "警告", "warrior": "战士",
    "wary": "谨慎的", "wash": "洗", "waste": "浪费",
    "waterfall": "瀑布", "wave": "波浪", "wax": "蜡",
    "weak": "弱的", "wealth": "财富", "wealthy": "富有的",
    "weave": "编织", "web": "网", "wedding": "婚礼",
    "weed": "杂草", "weekly": "每周的", "weep": "哭泣",
    "weird": "怪异的", "welcome": "欢迎", "welfare": "福利",
    "wellness": "健康", "wheel": "轮子", "whenever": "无论何时",
    "whereas": "而", "whip": "鞭子", "whisper": "低语",
    "whistle": "口哨", "wicked": "邪恶的", "widespread": "广泛的",
    "widow": "寡妇", "width": "宽度", "wild": "野生的",
    "wildlife": "野生动物", "willing": "愿意的", "willow": "柳树",
    "wind": "风", "wing": "翅膀", "wipe": "擦",
    "wire": "电线", "wisdom": "智慧", "wise": "明智的",
    "wit": "智慧", "withdraw": "撤回", "witness": "目击者",
    "wolves": "狼群", "wonderful": "精彩的", "wooden": "木制的",
    "wool": "羊毛", "workshop": "工作坊", "worm": "蠕虫",
    "worship": "崇拜", "worst": "最坏的", "wound": "伤口",
    "wrap": "包裹", "wreath": "花环", "wreck": "失事",
    "wrist": "手腕",
    "xenophobia": "仇外心理",
    "yacht": "游艇", "yell": "叫喊", "yield": "产量",
    "yoga": "瑜伽", "youth": "青年",
    "zeal": "热情", "zone": "区域", "zoo": "动物园",
}

def get_syllable_count(word):
    """简单估算音节数"""
    word = word.lower()
    vowels = "aeiou"
    count = 0
    prev_vowel = False
    for ch in word:
        is_vowel = ch in vowels
        if is_vowel and not prev_vowel:
            count += 1
        prev_vowel = is_vowel
    if word.endswith("e") and count > 1:
        count -= 1
    if word.endswith("le") and len(word) > 2:
        count += 0
    return max(1, count)

def main():
    # 读取现有词库（如果有）
    existing_words = {}
    try:
        with open("game/data/words.json", "r") as f:
            data = json.load(f)
            for w in data["words"]:
                existing_words[w["word"]] = w
        print(f"现有词库: {len(existing_words)} 个单词")
    except FileNotFoundError:
        print("未找到现有词库，从零开始构建")

    # 综合词库：MEANINGS 中的所有词
    all_word_set = set(existing_words.keys()) | set(MEANINGS.keys())

    # 确保 MEANINGS 中的词也是完整的
    words_list = []
    for word in sorted(all_word_set):
        meaning = MEANINGS.get(word, "")
        if not meaning:
            continue  # 跳过无释义的词
        words_list.append(word)

    print(f"综合词库共 {len(words_list)} 个单词")

    # 按词长分组 -> 组内打散（避免同字母聚集）-> 再按词长排序
    from itertools import groupby
    shuffled = []
    for length, group in groupby(sorted(words_list, key=len), key=len):
        group_words = list(group)
        random.shuffle(group_words)
        shuffled.extend(group_words)
    words_list = shuffled

    # 分配到50个难度等级
    total = len(words_list)
    levels = 50
    words_per_level = total // levels
    remainder = total % levels

    result_words = []
    idx = 0
    for level in range(1, levels + 1):
        count = words_per_level + (1 if level <= remainder else 0)
        level_words = words_list[idx:idx + count]
        idx += count

        for w in level_words:
            result_words.append({
                "id": 0,  # 后面重新编号
                "word": w,
                "meaning": MEANINGS.get(w, ""),
                "difficulty": level,
                "letter_count": len(w),
                "syllable_count": get_syllable_count(w),
            })

    # 在每关内随机打乱（混合字母顺序）
    random.seed(42)
    # 按 difficulty 分组，再在组内随机
    by_level = {}
    for w in result_words:
        by_level.setdefault(w["difficulty"], []).append(w)
    result_words = []
    for level in sorted(by_level.keys()):
        group = by_level[level]
        random.shuffle(group)
        result_words.extend(group)

    # 重新编号
    for i, w in enumerate(result_words):
        w["id"] = i + 1

    # 构建最终 JSON
    output = {
        "metadata": {
            "total_words": len(result_words),
            "total_levels": 50,
            "words_per_level": max(1, total // levels),
            "source": "Oxford 3000 + 新课标词汇 + 基础ESL词汇"
        },
        "words": result_words
    }

    with open("game/data/words.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)

    print(f"\n词库已保存: {len(result_words)} 个单词, {levels} 个难度等级")
    for level in range(1, min(11, levels + 1)):
        group = [w for w in result_words if w["difficulty"] == level]
        starts = set(w["word"][0] for w in group)
        print(f"  Level {level}: {len(group)} 词, 首字母: {sorted(starts)[:8]}")

    print(f"  ...")
    for level in range(45, 51):
        group = [w for w in result_words if w["difficulty"] == level]
        if group:
            starts = set(w["word"][0] for w in group)
            print(f"  Level {level}: {len(group)} 词, 首字母: {sorted(starts)[:8]}")

if __name__ == "__main__":
    main()
